### ISSUE TITLE
openfpm does not work with gcc 7.1.1

### ISSUE THREAD

**Issue by lucaswo** [incardon/openfpm_pdata#1]
After updating my gcc, `make` throws the following error:

```
In file included from ./Decomposition/CartDecomposition.hpp:33:0,
                 from Grid/grid_dist_id.hpp:20,
                 from main.cpp:34:
./Decomposition/Distribution/DistParMetisDistribution.hpp: In member function 'const DistParMetisDistribution<dim, T>& DistParMetisDistribution<dim, T>::operator=(const DistParMetisDistribution<dim, T>&&)':
./Decomposition/Distribution/DistParMetisDistribution.hpp:352:16: error: no matching function for call to 'DistGraph_CSR<nm_v, nm_e>::swap(const DistGraph_CSR<nm_v, nm_e>&)'
   g.swap(dist.g);
                ^
In file included from ./Decomposition/Distribution/DistParMetisDistribution.hpp:13:0,
                 from ./Decomposition/CartDecomposition.hpp:33,
                 from Grid/grid_dist_id.hpp:20,
                 from main.cpp:34:
./Graph/dist_map_graph.hpp:1919:14: note: candidate: void DistGraph_CSR<V, E, Memory, layout_v, layout_e, layout_v_base, layout_e_base, grow_p>::swap(DistGraph_CSR<V, E>&) [with V = nm_v; E = nm_e; Memory = HeapMemory; layout_v = memory_c<boost::fusion::vector<float [3], long unsigned int, long unsigned int, long unsigned int, long unsigned int, long int, long unsigned int>, memory>; layout_e = memory_c<boost::fusion::vector<long unsigned int, long unsigned int, long unsigned int>, memory>; layout_v_base = memory_traits_lin; layout_e_base = memory_traits_lin; grow_p = openfpm::grow_policy_double; typename memory_traits_lin<T>::type = memory_c<boost::fusion::vector<long unsigned int, long unsigned int, long unsigned int>, memory>; typename memory_traits_lin<T>::type = memory_c<boost::fusion::vector<float [3], long unsigned int, long unsigned int, long unsigned int, long unsigned int, long int, long unsigned int>, memory>] <near match>
  inline void swap(DistGraph_CSR<V, E> & g)
              ^~~~
./Graph/dist_map_graph.hpp:1919:14: note:   conversion of argument 1 would be ill-formed:
./Graph/dist_map_graph.hpp:1947:14: note: candidate: void DistGraph_CSR<V, E, Memory, layout_v, layout_e, layout_v_base, layout_e_base, grow_p>::swap(DistGraph_CSR<V, E>&&) [with V = nm_v; E = nm_e; Memory = HeapMemory; layout_v = memory_c<boost::fusion::vector<float [3], long unsigned int, long unsigned int, long unsigned int, long unsigned int, long int, long unsigned int>, memory>; layout_e = memory_c<boost::fusion::vector<long unsigned int, long unsigned int, long unsigned int>, memory>; layout_v_base = memory_traits_lin; layout_e_base = memory_traits_lin; grow_p = openfpm::grow_policy_double; typename memory_traits_lin<T>::type = memory_c<boost::fusion::vector<long unsigned int, long unsigned int, long unsigned int>, memory>; typename memory_traits_lin<T>::type = memory_c<boost::fusion::vector<float [3], long unsigned int, long unsigned int, long unsigned int, long unsigned int, long int, long unsigned int>, memory>] <near match>
  inline void swap(DistGraph_CSR<V, E> && g)
              ^~~~
./Graph/dist_map_graph.hpp:1947:14: note:   conversion of argument 1 would be ill-formed:
In file included from ./Decomposition/CartDecomposition.hpp:33:0,
                 from Grid/grid_dist_id.hpp:20,
                 from main.cpp:34:
./Decomposition/Distribution/DistParMetisDistribution.hpp:353:28: error: no matching function for call to 'openfpm::vector<long int>::swap(const openfpm::vector<long int>&)'
   vtxdist.swap(dist.vtxdist);
                            ^
In file included from ../openfpm_data/src/Vector/map_vector.hpp:152:0,
                 from Graph/CartesianGraphFactory.hpp:11,
                 from main.cpp:10:
../openfpm_data/src/Vector/map_vector_std.hpp:508:7: note: candidate: void openfpm::vector<T, HeapMemory, typename memory_traits_lin<T>::type, memory_traits_lin, openfpm::grow_policy_double, 1>::swap(std::vector<_RealType>&&) [with T = long int; typename memory_traits_lin<T>::type = void]
  void swap(std::vector<T> && v)
       ^~~~
../openfpm_data/src/Vector/map_vector_std.hpp:508:7: note:   no known conversion for argument 1 from 'const openfpm::vector<long int>' to 'std::vector<long int, std::allocator<long int> >&&'
../openfpm_data/src/Vector/map_vector_std.hpp:736:7: note: candidate: void openfpm::vector<T, HeapMemory, typename memory_traits_lin<T>::type, memory_traits_lin, openfpm::grow_policy_double, 1>::swap(openfpm::vector<T, HeapMemory, typename memory_traits_lin<T>::type, memory_traits_lin, openfpm::grow_policy_double, 1>&) [with T = long int; typename memory_traits_lin<T>::type = void] <near match>
  void swap(openfpm::vector<T,HeapMemory,layout,memory_traits_lin,grow_policy_double,STD_VECTOR> & v)
       ^~~~
../openfpm_data/src/Vector/map_vector_std.hpp:736:7: note:   conversion of argument 1 would be ill-formed:
../openfpm_data/src/Vector/map_vector_std.hpp:749:7: note: candidate: void openfpm::vector<T, HeapMemory, typename memory_traits_lin<T>::type, memory_traits_lin, openfpm::grow_policy_double, 1>::swap(openfpm::vector<T, HeapMemory, typename memory_traits_lin<T>::type, memory_traits_lin, openfpm::grow_policy_double, 1>&&) [with T = long int; typename memory_traits_lin<T>::type = void] <near match>
  void swap(openfpm::vector<T,HeapMemory,layout,memory_traits_lin,grow_policy_double,STD_VECTOR> && v)
       ^~~~
../openfpm_data/src/Vector/map_vector_std.hpp:749:7: note:   conversion of argument 1 would be ill-formed:
In file included from ./Decomposition/CartDecomposition.hpp:33:0,
                 from Grid/grid_dist_id.hpp:20,
                 from main.cpp:34:
./Decomposition/Distribution/DistParMetisDistribution.hpp:354:34: error: no matching function for call to 'openfpm::vector<openfpm::vector<long int> >::swap(const openfpm::vector<openfpm::vector<long int> >&)'
   partitions.swap(dist.partitions);
                                  ^
In file included from ../openfpm_data/src/Vector/map_vector.hpp:152:0,
                 from Graph/CartesianGraphFactory.hpp:11,
                 from main.cpp:10:
../openfpm_data/src/Vector/map_vector_std.hpp:508:7: note: candidate: void openfpm::vector<T, HeapMemory, typename memory_traits_lin<T>::type, memory_traits_lin, openfpm::grow_policy_double, 1>::swap(std::vector<_RealType>&&) [with T = openfpm::vector<long int>; typename memory_traits_lin<T>::type = void]
  void swap(std::vector<T> && v)
       ^~~~
../openfpm_data/src/Vector/map_vector_std.hpp:508:7: note:   no known conversion for argument 1 from 'const openfpm::vector<openfpm::vector<long int> >' to 'std::vector<openfpm::vector<long int>, std::allocator<openfpm::vector<long int> > >&&'
../openfpm_data/src/Vector/map_vector_std.hpp:736:7: note: candidate: void openfpm::vector<T, HeapMemory, typename memory_traits_lin<T>::type, memory_traits_lin, openfpm::grow_policy_double, 1>::swap(openfpm::vector<T, HeapMemory, typename memory_traits_lin<T>::type, memory_traits_lin, openfpm::grow_policy_double, 1>&) [with T = openfpm::vector<long int>; typename memory_traits_lin<T>::type = void] <near match>
  void swap(openfpm::vector<T,HeapMemory,layout,memory_traits_lin,grow_policy_double,STD_VECTOR> & v)
       ^~~~
../openfpm_data/src/Vector/map_vector_std.hpp:736:7: note:   conversion of argument 1 would be ill-formed:
../openfpm_data/src/Vector/map_vector_std.hpp:749:7: note: candidate: void openfpm::vector<T, HeapMemory, typename memory_traits_lin<T>::type, memory_traits_lin, openfpm::grow_policy_double, 1>::swap(openfpm::vector<T, HeapMemory, typename memory_traits_lin<T>::type, memory_traits_lin, openfpm::grow_policy_double, 1>&&) [with T = openfpm::vector<long int>; typename memory_traits_lin<T>::type = void] <near match>
  void swap(openfpm::vector<T,HeapMemory,layout,memory_traits_lin,grow_policy_double,STD_VECTOR> && v)
       ^~~~
../openfpm_data/src/Vector/map_vector_std.hpp:749:7: note:   conversion of argument 1 would be ill-formed:
In file included from ./Decomposition/CartDecomposition.hpp:33:0,
                 from Grid/grid_dist_id.hpp:20,
                 from main.cpp:34:
./Decomposition/Distribution/DistParMetisDistribution.hpp:355:34: error: no matching function for call to 'openfpm::vector<openfpm::vector<long unsigned int> >::swap(const openfpm::vector<openfpm::vector<long unsigned int> >&)'
   v_per_proc.swap(dist.v_per_proc);
                                  ^
In file included from ../openfpm_data/src/Vector/map_vector.hpp:152:0,
                 from Graph/CartesianGraphFactory.hpp:11,
                 from main.cpp:10:
../openfpm_data/src/Vector/map_vector_std.hpp:508:7: note: candidate: void openfpm::vector<T, HeapMemory, typename memory_traits_lin<T>::type, memory_traits_lin, openfpm::grow_policy_double, 1>::swap(std::vector<_RealType>&&) [with T = openfpm::vector<long unsigned int>; typename memory_traits_lin<T>::type = void]
  void swap(std::vector<T> && v)
       ^~~~
../openfpm_data/src/Vector/map_vector_std.hpp:508:7: note:   no known conversion for argument 1 from 'const openfpm::vector<openfpm::vector<long unsigned int> >' to 'std::vector<openfpm::vector<long unsigned int>, std::allocator<openfpm::vector<long unsigned int> > >&&'
../openfpm_data/src/Vector/map_vector_std.hpp:736:7: note: candidate: void openfpm::vector<T, HeapMemory, typename memory_traits_lin<T>::type, memory_traits_lin, openfpm::grow_policy_double, 1>::swap(openfpm::vector<T, HeapMemory, typename memory_traits_lin<T>::type, memory_traits_lin, openfpm::grow_policy_double, 1>&) [with T = openfpm::vector<long unsigned int>; typename memory_traits_lin<T>::type = void] <near match>
  void swap(openfpm::vector<T,HeapMemory,layout,memory_traits_lin,grow_policy_double,STD_VECTOR> & v)
       ^~~~
../openfpm_data/src/Vector/map_vector_std.hpp:736:7: note:   conversion of argument 1 would be ill-formed:
../openfpm_data/src/Vector/map_vector_std.hpp:749:7: note: candidate: void openfpm::vector<T, HeapMemory, typename memory_traits_lin<T>::type, memory_traits_lin, openfpm::grow_policy_double, 1>::swap(openfpm::vector<T, HeapMemory, typename memory_traits_lin<T>::type, memory_traits_lin, openfpm::grow_policy_double, 1>&&) [with T = openfpm::vector<long unsigned int>; typename memory_traits_lin<T>::type = void] <near match>
  void swap(openfpm::vector<T,HeapMemory,layout,memory_traits_lin,grow_policy_double,STD_VECTOR> && v)
       ^~~~
../openfpm_data/src/Vector/map_vector_std.hpp:749:7: note:   conversion of argument 1 would be ill-formed:
make[1]: *** [Makefile:596: pdata-main.o] Error 1
```

The same error appears, whilst trying to reinstall openfpm via `./install`.

**Comment by incardon** [comment]
Thanks for reporting I will check the problem and produce a patch

**Comment by incardon** [comment]
In  openfpm_pdata/src/Decomposition/Distribution/DistParMetisDistribution.hpp 

change from

const DistParMetisDistribution<dim, T> & operator=(const DistParMetisDistribution<dim, T> && dist)

to


const DistParMetisDistribution<dim, T> & operator=(DistParMetisDistribution<dim, T> && dist)



[Release_0.8.0_gcc_7.1.1.txt](https://github.com/incardon/openfpm_pdata/files/1058575/Release_0.8.0_gcc_7.1.1.txt)

**Comment by lucaswo** [comment]
Thanks for the quick response. Everything is functional again.
